import React, { createContext, useContext, useState } from 'react';

const content = {
  en: {
    // Header
    studioTag: "INDEPENDENT GROWTH STUDIO",
    navProblem: "Problem",
    navDisciplines: "Disciplines",
    navSystems: "Systems",
    navVerticals: "Verticals",
    navApproach: "Approach",
    navOutcomes: "Outcomes",
    navContact: "Contact",
    bookConsultation: "Book Consultation",

    // Hero
    heroEyebrow: "SATURN GROWTH SYSTEMS ◆ INDEPENDENT STUDIO",
    heroH1Part1: "WE SOLVE BUSINESS PROBLEMS.",
    heroH1Part2: "you grow.",
    heroSub: "Your business does not need more technology just for the sake of technology. It needs more customers, more enquiries, better operations, and more revenue. That is where Saturn Growth Systems comes in.",
    heroCtaPrimary: "Book a Growth Consultation",
    heroCtaSecondary: "Tell Us Your Problem",
    heroConsoleBadge: "SATURN TELEMETRY CONSOLE // ORBITAL NODE ACTIVE",
    heroConsoleDiscipline: "DISCIPLINE: GROWTH SYSTEMS ARCHITECTURE",

    // Section 2: Problem / Approach
    sec2Tag: "[ OUR APPROACH // WHAT GUIDES THE WORK ]",
    sec2SectionNum: "SECTION 02",
    sec2Pill: "Our Approach / What guides the work",
    sec2TitlePart1: "Your Problem Comes First.",
    sec2TitlePart2: "Our Solution Comes Second.",
    sec2Lead: "Most agencies sell what they already know how to build. We work differently: we first diagnose the bottleneck, then build only what moves revenue.",
    sec2QTitle: "01 // ROOT-CAUSE DIAGNOSIS",
    sec2Q1: "Where are customers dropping off before buying?",
    sec2Q2: "Where are high-intent leads getting lost or delayed?",
    sec2Q3: "What repetitive tasks drain your team's hours every day?",
    sec2SolTitle: "02 // BESPOKE SYSTEMS BUILD",
    sec2Sol1: "Zero bloated features or fragile code packages.",
    sec2Sol2: "No complicated technical jargon. Just clear business ROI.",
    sec2Sol3: "Tailored systems engineered strictly around your pipeline.",
    sec2P1: "Most agencies sell what they already know how to build. We work differently. We first understand what is costing you customers, where leads get lost, and what drains your team's time.",
    sec2P2: "Then we design and implement the solution that addresses the real problem. No unnecessary features. No one-size-fits-all packages. Just solutions built around your business.",
    diagSculptureTag: "01 ◆ SATURN DIAGNOSTIC PROTOCOL",
    diagSculptureTitle: "Proprietary Root-Cause Systems Audit",

    // Diagnostic Leak Rail
    q1Num: "01 // LEAKAGE",
    q1Title: "Costing Customers?",
    q1Desc: "Unclear messaging, delayed responses, friction in checkouts, or lack of social proof that repels buyers.",
    q2Num: "02 // DROPOFF",
    q2Title: "Lost Leads?",
    q2Desc: "Messages left unread, slow follow-ups, lost inquiries between reps, or no automated retargeting loop.",
    q3Num: "03 // DRAG",
    q3Title: "Team Time Waste?",
    q3Desc: "Manual data entry, repetitive phone calls, compiling reports manually, and endless admin coordination.",
    q4Num: "04 // AUTOMATION",
    q4Title: "Automatable Friction?",
    q4Desc: "Instant customer responses, appointment booking, invoices, client onboarding, and automated reminders.",
    q5Num: "05 // CEILING",
    q5Title: "Growth Bottlenecks?",
    q5Desc: "Inconsistent leads, poor conversion rates, operational chaos when volume increases, or lacking modern software.",

    // Section 3: Systems
    sec3Tag: "[ SELECTED SYSTEMS // 03 ]",
    sec3TitlePart1: "WORK THAT",
    sec3TitlePart2: "speaks for itself",
    sec3Archive: "OPERATIONAL ARCHIVES // 01 / 04",
    sys1Tag: "01 ◆ ENTERPRISE TELEMETRY",
    sys1Title: "ENTERPRISE REVENUE TELEMETRY & COMMAND CENTER",
    sys1Desc: "Real-time pipeline monitoring, automated multi-display sync, conversion anomaly detection, and unified executive metrics.",
    sys2Tag: "02 ◆ SATURN CORE NODE",
    sys2Title: "PROPRIETARY BUSINESS BACKBONE",
    sys2Desc: "High-throughput data orchestration server, custom automated pipelines, sub-second trigger engine, and secure offline failover.",
    sys3Tag: "03 ◆ OMNICHANNEL CONSOLE",
    sys3Title: "AUTONOMOUS LEAD ROUTING & GLASS CONSOLE",
    sys3Desc: "Dynamic intake app, instant automated qualification, synced CRM dispatch, and real-time deal alerts directly to phones.",
    sys4Tag: "04 ◆ EXECUTIVE DECISION ENGINE",
    sys4Title: "EXECUTIVE GROWTH ARCHITECTURE & DECISION ENGINE",
    sys4Desc: "Multi-department operations alignment, data-backed roadmap execution, and synchronized automated reporting for leadership.",

    // Section 4: Disciplines
    sec4Tag: "[ COMPREHENSIVE CAPABILITIES // 04 ]",
    sec4Badge: "9 DISCIPLINES",
    sec4TitlePart1: "DISCIPLINES",
    sec4TitlePart2: "that move together",
    srv1Title: "Websites & Digital Presence",
    srv1Pill: "Fast ◆ High-Converting ◆ Mobile-First",
    srv1Desc: "Websites built for speed, immediate customer trust, and seamless enquiry generation. Includes custom portfolio portals, sales landing pages, and institutional web presences engineered to convert visitors into phone calls and booked appointments.",
    srv2Title: "Marketing & Lead Generation",
    srv2Pill: "Meta Ads ◆ Google Funnels ◆ Inbound Flow",
    srv2Desc: "Paid ad funnels, search visibility, high-intent lead magnets, and automated customer qualification that brings serious buyers to your door rather than casual clickers.",
    srv3Title: "Social Media Management",
    srv3Pill: "Content ◆ Short-Form Video ◆ Category Authority",
    srv3Desc: "Consistent, high-quality content production and brand positioning that builds unquestioned authority, establishes client trust, and keeps your company top-of-mind.",
    srv4Title: "AI & Chat Assistants",
    srv4Pill: "24/7 WhatsApp API ◆ Instant Response ◆ Zero Lag",
    srv4Desc: "Smart WhatsApp and website bots that answer enquiries in under 5 seconds, capture customer contact info, qualify requests, and pass warm leads directly to your sales team.",
    srv5Title: "Voice & Calling Systems",
    srv5Pill: "Zero Missed Calls ◆ Smart IVR ◆ Auto Reminders",
    srv5Desc: "Automated phone systems and voice bots that ensure zero missed calls, handle routine customer questions, schedule meetings on your calendar, and send automatic follow-up reminders.",
    srv6Title: "Custom Apps & Software",
    srv6Pill: "Bespoke CRMs ◆ Client Portals ◆ Internal Tools",
    srv6Desc: "Software built around how you actually work — custom customer portals, quotation engines, internal tracking dashboards, and management apps that off-the-shelf software can't provide.",
    srv7Title: "Business Automation",
    srv7Pill: "Make / Webhooks ◆ Seamless Sync ◆ 0 Manual Work",
    srv7Desc: "Connect your tools together. Invoices that send themselves, contracts auto-generated upon payment, and notification systems that update your team instantly with zero manual intervention.",
    srv8Title: "AI-Powered Business Systems",
    srv8Pill: "Intelligent Workflows ◆ Document AI ◆ Telemetry",
    srv8Desc: "Integrating modern AI models into daily operations: document scanning, customer categorization, intelligent routing, and predictive business recommendations designed for operational efficiency.",
    srv9Title: "Growth Consultancy",
    srv9Pill: "Fractional CTO ◆ Tech Strategy ◆ Roadmap",
    srv9Desc: "Strategic technology advice from someone who understands commercial business reality. We audit existing systems, identify high-leverage growth levers, and chart the cleanest route forward.",
    bannerTag: "◆ SIGNATURE COMMITMENT",
    bannerQuotePart1: "\"Your problem doesn't have to fit our products.",
    bannerQuotePart2: "Our solution has to fit your problem.\"",
    bannerDesc: "If what you need is not in the list above, that is exactly where we do our best work. We study the problem, map the solution, and build what is required.",
    bannerBtn: "Custom Build Enquiry →",

    // Section 5: Verticals
    sec5Tag: "[ TARGET SECTORS // 05 ]",
    sec5Badge: "WHO WE SERVE",
    sec5TitlePart1: "BUILT FOR BUSINESSES",
    sec5TitlePart2: "that want to grow",
    sec5Sub: "We work with businesses of all sizes and across industries. You don't need to be a technology company — you just need an ambition to grow.",
    v1Num: "01 // ADMISSIONS & EDUCATION",
    v1Title: "Schools & Educational Institutions",
    v1Desc: "More admissions, automated parent inquiry bots, WhatsApp pipelines, and prestigious digital positioning.",
    v1Tag1: "Parent Inquiry Bots",
    v1Tag2: "Admissions CRM",
    v2Num: "02 // PROPERTY & ASSETS",
    v2Title: "Real Estate Businesses",
    v2Desc: "Qualified buyer lead capture, automated site-visit calendar sync, property inquiry dispatchers, and CRM tracking.",
    v2Tag1: "Tour Booking",
    v2Tag2: "High-Value Ads",
    v3Num: "03 // MULTI-LOCATION",
    v3Title: "Franchise Owners",
    v3Desc: "Standardized lead capture, localized marketing playbooks, and unified multi-location dashboard management.",
    v3Tag1: "Centralized KPI Hub",
    v3Tag2: "Brand Uniformity",
    v4Num: "04 // FAST SCALING",
    v4Title: "Founders & Growing Companies",
    v4Desc: "Complete digital ecosystems built fast from zero to scale without bloated engineering agency payroll.",
    v4Tag1: "Zero-to-Scale",
    v4Tag2: "Fractional Tech Team",
    v5Num: "05 // REINVENTION & MODERNIZATION",
    v5Title: "Local & Established Businesses",
    v5Desc: "Modernize legacy client touchpoints, dominate local search, replace chaotic WhatsApp groups with integrated CRM automations, and eliminate administrative drag.",
    v5Tag1: "Legacy Upgrade",
    v5Tag2: "Local Search SEO",
    v5Tag3: "Ops Modernization",
    vertNote: "And when your industry is different, that is not a problem.",
    vertNoteBold: "We learn the business first.",

    // Section 6: Approach
    sec6Tag: "[ HOW WE WORK // 06 ]",
    sec6Badge: "5-STEP PROTOCOL",
    sec6TitlePart1: "OUR",
    sec6TitlePart2: "approach",
    st1Title: "Understand",
    st1Desc: "We listen. We ask deep questions about your day-to-day operations, cash friction, and existing bottlenecks.",
    st1Phase: "PHASE // AUDIT",
    st2Title: "Diagnose",
    st2Desc: "We pinpoint the exact issue. Is it visibility, qualification speed, trust deficit, or conversion follow-up?",
    st2Phase: "PHASE // ROOT CAUSE",
    st3Title: "Design",
    st3Desc: "We propose the leanest, most effective solution. Nothing bloated, nothing unneeded—pure structural clarity.",
    st3Phase: "PHASE // BLUEPRINT",
    st4Title: "Build",
    st4Desc: "We build, configure, test, and deploy fast. Clean code, rock-solid integrations, high aesthetic authority.",
    st4Phase: "PHASE // PRODUCTION",
    st5Title: "Grow",
    st5Desc: "We monitor outputs, refine conversion metrics, train your team, and support your continuous upward trajectory.",
    st5Phase: "PHASE // EXPANSION",

    // Section 7: Why Saturn
    sec7Tag: "[ COMPETITIVE LEVERAGE // 07 ]",
    sec7Badge: "WHY SATURN",
    sec7TitlePart1: "WHY",
    sec7TitlePart2: "saturn?",
    sec7Sub: "We replace the friction of traditional bloated agencies with disciplined, outcome-first engineering.",
    ws1Title: "Faster",
    ws1Desc: "Rapid deployment cycles. We launch working systems in days and weeks rather than spending quarters inside endless slide decks.",
    ws2Title: "Practical",
    ws2Desc: "No unnecessary technical jargon or vanity software tools. We only implement architectures that directly move commercial needles.",
    ws3Title: "Cost-Effective",
    ws3Desc: "Fraction of the cost of building an in-house engineering squad or retaining multiple disjointed marketing and tech agencies.",
    ws4Title: "High Quality",
    ws4Desc: "Elite digital craft with precision engineering, clean codebase integrity, sub-second response times, and supreme aesthetic authority.",
    ws5Title: "End-to-End Support",
    ws5Desc: "We don't vanish after project launch. We train your staff, monitor daily operations, and actively support your ongoing expansion.",
    ws6Title: "One Partner. Multiple Solutions.",
    ws6Desc: "From web presence and ad campaigns to automated telephony and custom internal portals—all unified under one technical partner.",

    // Section 8: Outcomes
    sec8Tag: "[ THE PROMISE // 08 ]",
    sec8Badge: "REAL IMPACT",
    sec8TitlePart1: "WE DON'T JUST BUILD THINGS.",
    sec8TitlePart2: "we build business outcomes.",
    out1Title: "MORE ENQUIRIES",
    out1Sub: "Frictionless discovery funnel",
    out2Title: "MORE CUSTOMERS",
    out2Sub: "Immediate trust conversion",
    out3Title: "MORE SALES",
    out3Sub: "Automated pipeline velocity",
    out4Title: "LESS WASTED TIME",
    out4Sub: "Autonomous operations",
    out5Title: "BETTER OPERATIONS",
    out5Sub: "Zero human lag or leakage",
    out6Title: "HIGHER REVENUE",
    out6Sub: "Predictable compounding scale",

    // Section 10: Contact
    sec10Tag: "[ INQUIRY CONSOLE // 10 ]",
    sec10Badge: "PROJECT DESK",
    sec10TitlePart1: "LET'S FIND WHAT'S",
    sec10TitlePart2: "holding your business back.",
    sec10Sub: "Tell us about your business, your current challenges and where you want to go. We'll help you identify where the biggest opportunities are and what can be done about them.",
    mottoP1: "Understand the problem.",
    mottoP2: "Build the solution.",
    mottoP3: "Create the growth.",
    inquiryDeskTitle: "DIRECT INQUIRY DESK",
    auditTitle: "DISCOVERY PROTOCOL",
    auditDesc: "Initial 30-Min Systems Audit",
    auditBadge: "NO CHARGE",
    contactEmail: "saturngrowthsystems@gmail.com",
    primaryPhone: "+91 79826 68530",
    alternatePhone: "+91 87440 03727",
    whatsappLink: "https://wa.me/917982668530?text=Hi%20Saturn%20Growth%20Systems%2C%20I%20would%20like%20to%20book%20a%20systems%20audit.",
    whatsappAlternateLink: "https://wa.me/918744003727?text=Hi%20Saturn%20Growth%20Systems%2C%20I%20would%20like%20to%20book%20a%20systems%20audit.",
    lblName: "Your Full Name *",
    lblComp: "Business / Company *",
    lblContact: "Email or Phone *",
    lblBizdesc: "What Does Your Business Do? *",
    lblProblem: "What Problem Are You Trying To Solve?",
    phName: "e.g. Rahul Mehta",
    phComp: "e.g. Apex Enterprises",
    phContact: "saturngrowthsystems@gmail.com or +91 79826 68530",
    phBizdesc: "e.g. Private school with 800+ students, or Multi-city real estate brokerage...",
    phProblem: "Describe where customers are dropping off, what is draining your team's time, or what you want automated...",
    btnSend: "Book a Growth Consultation →",
    formSuccessTitle: "AUDIT BRIEF DISPATCHED",
    formSuccessMsg: "Our Lead Growth Architect will review your bottleneck and contact you within 2 business hours.",

    // Footer
    footerMotto: "Understand the problem. Build the solution. Create the growth.",
    footerScale: "ENGINEERED FOR COMPOUNDING SCALE"
  },
  hi: {
    // Header
    studioTag: "INDEPENDENT GROWTH STUDIO",
    navProblem: "Problem",
    navDisciplines: "Disciplines",
    navSystems: "Systems",
    navVerticals: "Industries",
    navApproach: "Approach",
    navOutcomes: "Outcomes",
    navContact: "Contact",
    bookConsultation: "Consultation Book Karein",

    // Hero
    heroEyebrow: "SATURN GROWTH SYSTEMS ◆ INDEPENDENT GROWTH STUDIO",
    heroH1Part1: "HUM BUSINESS PROBLEMS SOLVE KARTE HAIN.",
    heroH1Part2: "aap grow karte hain.",
    heroSub: "Aapke business ko bina zarurat ke faltu tools nahi chahiye. Isko chahiye zyada customers, verified inquiries, smooth operations aur predictable revenue growth. Yahi deliver karta hai Saturn Growth Systems.",
    heroCtaPrimary: "Growth Consultation Book Karein",
    heroCtaSecondary: "Humein Apni Problem Batayein",
    heroConsoleBadge: "SATURN TELEMETRY CONSOLE // ORBITAL NODE ACTIVE",
    heroConsoleDiscipline: "DISCIPLINE: GROWTH SYSTEMS ARCHITECTURE",

    // Section 2: Problem / Approach
    sec2Tag: "[ HAMARA APPROACH // KAAM KAISE HOTA HAI ]",
    sec2SectionNum: "SECTION 02",
    sec2Pill: "Hamara Approach / What guides the work",
    sec2TitlePart1: "Aapki Problem Pehle Aati Hai.",
    sec2TitlePart2: "Hamara Solution Baad Mein.",
    sec2Lead: "Zyadatar agencies wahi bechti hain jo unke paas pehle se tayar hai. Hum alag kaam karte hain: pehle dikkat samajhte hain, fir wahi build karte hain jisse revenue grow ho.",
    sec2QTitle: "01 // ROOT-CAUSE AUDIT",
    sec2Q1: "Customers kahan kho rahe hain aur revenue kahan leak ho raha hai?",
    sec2Q2: "High-intent leads kahan miss ya slow follow-up me fas rahi hain?",
    sec2Q3: "Team ka kitna valuable time daily repetitive tasks me waste ho raha hai?",
    sec2SolTitle: "02 // BESPOKE SOLUTIONS",
    sec2Sol1: "Bina faltu features ya unnecessary bloated packages.",
    sec2Sol2: "Koi complicated technical jargon nahi, seedha practical kaam.",
    sec2Sol3: "Sirf aapke specific business aur conversion goals ke mutabiq custom systems.",
    sec2P1: "Zyadatar agencies wo bechti hain jo unke paas pehle se tayar hai. Hum pehle samajhte hain: Customers kahan kho rahe hain? Leads kahan phas rahi hain? Team ka time kahan waste hota hai?",
    sec2P2: "Phir hum seedhe wahi solution banate hain jo aapki real problem ko theek kare. Koi faltu technical jargon nahi, sirf aapke business ke mutabik engineered systems.",
    diagSculptureTag: "01 ◆ SATURN DIAGNOSTIC PROTOCOL",
    diagSculptureTitle: "Proprietary Root-Cause Systems Audit",

    // Diagnostic Leak Rail
    q1Num: "01 // CUSTOMER DROP-OFF",
    q1Title: "Customers Kho Rahe Hain?",
    q1Desc: "Slow response speed, confusing website ya trust ki kami jo potential buyers ko wapas bhej deti hai.",
    q2Num: "02 // LEAD DROP",
    q2Title: "Leads Miss Ho Rahi Hain?",
    q2Desc: "Unanswered WhatsApp messages, late sales calls aur automated follow-up loop na hona.",
    q3Num: "03 // TIME DRAIN",
    q3Title: "Team Ka Time Waste Ho Raha Hai?",
    q3Desc: "Manual Excel entry, bar-bar routine phone calls, aur unnecessary administrative paper trail.",
    q4Num: "04 // AUTOMATION",
    q4Title: "Repetitive Kaam Automate Karein",
    q4Desc: "Instant 24/7 customer chat reply, calendar booking, automated invoices aur payment reminders.",
    q5Num: "05 // SCALE CEILING",
    q5Title: "Business Growth Ruki Hui Hai?",
    q5Desc: "Inconsistent leads, poor conversion rates, ya purana outdated software jo badhte volume ko handle nahi kar pata.",

    // Section 3: Systems
    sec3Tag: "[ SELECTED SYSTEMS // 03 ]",
    sec3TitlePart1: "KAAM JO",
    sec3TitlePart2: "khud bolta hai",
    sec3Archive: "OPERATIONAL ARCHIVES // 01 / 04",
    sys1Tag: "01 ◆ ENTERPRISE TELEMETRY",
    sys1Title: "ENTERPRISE REVENUE TELEMETRY & COMMAND CENTER",
    sys1Desc: "Real-time pipeline monitoring, automated multi-display sync, conversion anomaly detection aur unified executive metrics.",
    sys2Tag: "02 ◆ SATURN CORE NODE",
    sys2Title: "PROPRIETARY BUSINESS BACKBONE",
    sys2Desc: "High-throughput data orchestration server, custom automated pipelines, sub-second trigger engine aur secure failover.",
    sys3Tag: "03 ◆ OMNICHANNEL CONSOLE",
    sys3Title: "AUTONOMOUS LEAD ROUTING & GLASS CONSOLE",
    sys3Desc: "Dynamic intake app, instant automated qualification, synced CRM dispatch aur real-time deal alerts seedhe phone par.",
    sys4Tag: "04 ◆ EXECUTIVE DECISION ENGINE",
    sys4Title: "EXECUTIVE GROWTH ARCHITECTURE & DECISION ENGINE",
    sys4Desc: "Multi-department operations alignment, data-backed roadmap execution aur synchronized automated leadership reports.",

    // Section 4: Disciplines
    sec4Tag: "[ COMPREHENSIVE CAPABILITIES // 04 ]",
    sec4Badge: "9 DISCIPLINES",
    sec4TitlePart1: "DISCIPLINES",
    sec4TitlePart2: "jo ek sath kaam karti hain",
    srv1Title: "High-Converting Websites & Digital Presence",
    srv1Pill: "Fast ◆ High-Converting ◆ Mobile-First",
    srv1Desc: "Super-fast websites jo pehli nazar me customer trust banati hain aur confirmed inquiry calls generate karti hain. Sales landing pages aur portfolio portals.",
    srv2Title: "Targeted Marketing & Lead Generation",
    srv2Pill: "Meta Ads ◆ Google Funnels ◆ Inbound Flow",
    srv2Desc: "Targeted Meta aur Google ad funnels jo cold traffic ko serious buyers aur booked consultation appointments me convert karte hain.",
    srv3Title: "Social Media & Brand Authority",
    srv3Pill: "Content ◆ Short-Form Video ◆ Category Authority",
    srv3Desc: "High-production short video content aur strategic storytelling jo aapke business ko industry me category leader banati hai.",
    srv4Title: "AI & 24/7 WhatsApp Chatbots",
    srv4Pill: "24/7 WhatsApp API ◆ Instant Response ◆ Zero Lag",
    srv4Desc: "Smart 24/7 WhatsApp bots jo 5 seconds me reply dekar leads qualify karte hain aur warm leads seedhe sales team ko push karte hain.",
    srv5Title: "Automated Voice & Calling Systems",
    srv5Pill: "Zero Missed Calls ◆ Smart IVR ◆ Auto Reminders",
    srv5Desc: "Smart AI telephony jo busy time pe zero calls miss hone deti hai aur routine queries solve karke meeting calendar schedule karti hai.",
    srv6Title: "Custom Apps & Tailor-Made Software",
    srv6Pill: "Bespoke CRMs ◆ Client Portals ◆ Internal Tools",
    srv6Desc: "Aapke workflow ke mutabik custom client portals, quotation engines, internal tracking dashboards aur tailor-made software.",
    srv7Title: "End-to-End Business Automation",
    srv7Pill: "Make / Webhooks ◆ Seamless Sync ◆ 0 Manual Work",
    srv7Desc: "Aapke sabhi tools sync — automated contract creation, payment hot-triggers aur team notification bina kisi manual error ke.",
    srv8Title: "AI-Powered Business Systems",
    srv8Pill: "Intelligent Workflows ◆ Document AI ◆ Telemetry",
    srv8Desc: "Modern AI models ka integration: document parsing, customer classification, automated lead dispatch aur predictive growth recommendations.",
    srv9Title: "Strategic Growth Consultancy",
    srv9Pill: "Fractional CTO ◆ Tech Strategy ◆ Roadmap",
    srv9Desc: "Fractional CTO aur practical commercial technology strategy jo business friction ko identify karke direct growth path banati hai.",
    bannerTag: "◆ SIGNATURE COMMITMENT",
    bannerQuotePart1: "\"Aapki problem ko hamare products me fit nahi hona.",
    bannerQuotePart2: "Hamare solution ko aapki problem solve karni hai.\"",
    bannerDesc: "Agar aapki requirement upar di gayi list me nahi hai, toh wahi hamara core expertise hai. Humein batayein kya problem hai, solution hum banayenge.",
    bannerBtn: "Bespoke Project Discuss Karein →",

    // Section 5: Verticals
    sec5Tag: "[ TARGET SECTORS // 05 ]",
    sec5Badge: "WHO WE SERVE",
    sec5TitlePart1: "UN SABHI BUSINESSES KE LIYE",
    sec5TitlePart2: "jo scale karna chahte hain",
    sec5Sub: "Hum har industry aur har size ke business ke saath judte hain. Aapko tech company hone ki zarurat nahi hai — bas grow karne ka ambition hona chahiye.",
    v1Num: "01 // ADMISSIONS & EDUCATION",
    v1Title: "Schools aur Coaching Institutes",
    v1Desc: "Zyada verified admissions, automated parent inquiry bots aur modern prestige digital presence.",
    v1Tag1: "Parent Inquiry Bots",
    v1Tag2: "Admissions CRM",
    v2Num: "02 // PROPERTY & ASSETS",
    v2Title: "Real Estate Builders aur Property Firms",
    v2Desc: "Verified buyer leads, automated site-visit calendar sync aur direct high-ticket CRM lead dispatch.",
    v2Tag1: "Site-Visit Booking",
    v2Tag2: "High-Intent Meta Ads",
    v3Num: "03 // MULTI-LOCATION",
    v3Title: "Franchise aur Multi-Outlet Brands",
    v3Desc: "Standardized lead capture, localized marketing playbooks aur unified multi-location dashboards.",
    v3Tag1: "Centralized KPI Hub",
    v3Tag2: "Brand Consistency",
    v4Num: "04 // FAST SCALING",
    v4Title: "Founders aur High-Growth Startups",
    v4Desc: "Bina kisi bloated tech team payroll ke complete digital ecosystem zero-to-scale tezi se build karein.",
    v4Tag1: "Zero-to-Scale",
    v4Tag2: "Fractional Tech Team",
    v5Num: "05 // REINVENTION & MODERNIZATION",
    v5Title: "Local Vyapaar aur Established Businesses",
    v5Desc: "Manual paperwork aur WhatsApp chaos khatam karein, modern CRM lagayein aur local search me dominate karein.",
    v5Tag1: "Legacy Upgrade",
    v5Tag2: "Local Search SEO",
    v5Tag3: "Ops Modernization",
    vertNote: "Aur agar aapki industry bilkul alag hai, koi dikkat nahi.",
    vertNoteBold: "Hum pehle aapka business model samajhte hain.",

    // Section 6: Approach
    sec6Tag: "[ HOW WE WORK // 06 ]",
    sec6Badge: "5-STEP PROTOCOL",
    sec6TitlePart1: "HAMARA",
    sec6TitlePart2: "5-step protocol",
    st1Title: "Samajhna (Deep Audit)",
    st1Desc: "Hum dhyan se sunte hain aur aapke daily operations ki actual reality aur operational friction note karte hain.",
    st1Phase: "PHASE // AUDIT",
    st2Title: "Diagnose Karna (Root Cause)",
    st2Desc: "Asli dikkat kahan hai: visibility me, response speed me, ya conversion follow-up me?",
    st2Phase: "PHASE // ROOT CAUSE",
    st3Title: "Design Karna (Lean Blueprint)",
    st3Desc: "Sabse direct aur high-leverage solution design karte hain. No extra fluff, no useless tools.",
    st3Phase: "PHASE // BLUEPRINT",
    st4Title: "Build & Deploy (Fast Production)",
    st4Desc: "Tezi se build, test aur deploy karte hain. Clean code aur reliable rock-solid engineering.",
    st4Phase: "PHASE // PRODUCTION",
    st5Title: "Scale & Grow (Continuous Trajectory)",
    st5Desc: "Results track karte hain, conversion metrics refine karte hain aur aapki team ko continuous support dete hain.",
    st5Phase: "PHASE // EXPANSION",

    // Section 7: Why Saturn
    sec7Tag: "[ COMPETITIVE LEVERAGE // 07 ]",
    sec7Badge: "WHY SATURN",
    sec7TitlePart1: "KYUN",
    sec7TitlePart2: "saturn?",
    sec7Sub: "Hum traditional bloated agencies ke lambe chakkaron ko outcome-driven disciplined engineering se replace karte hain.",
    ws1Title: "Tez Delivery (Days, Not Quarters)",
    ws1Desc: "Hafton aur mahino ke lambe slide decks ke bajaye kuch hi dino me fully working systems live ho jate hain.",
    ws2Title: "Seedha Practical Kaam (No Jargon)",
    ws2Desc: "Bina kisi faaltu technical jargon ke wahi tools implement karte hain jo aapka commercial revenue badhate hain.",
    ws3Title: "Kifayati aur High-ROI",
    ws3Desc: "Multiple fragmented agencies ya expensive in-house tech team rakhne se bohot zyada cost-effective.",
    ws4Title: "Top Engineering Quality",
    ws4Desc: "Precision engineering, sub-second response time, ultra-clean code aur supreme visual authority.",
    ws5Title: "End-to-End Team Support",
    ws5Desc: "Launch ke baad gayab nahi hote. Aapki team ko train karte hain aur daily operations support karte hain.",
    ws6Title: "Ek Hi Partner, Saare Solutions",
    ws6Desc: "Websites, Meta ads, WhatsApp bots se lekar custom software tak — sab ek hi reliable partner ke sath.",

    // Section 8: Outcomes
    sec8Tag: "[ THE PROMISE // 08 ]",
    sec8Badge: "REAL IMPACT",
    sec8TitlePart1: "HUM SIRF TOOLS NAHI BANATE.",
    sec8TitlePart2: "hum business outcomes banate hain.",
    out1Title: "ZYADA INQUIRIES",
    out1Sub: "Bina kisi rukawat ke continuous discovery",
    out2Title: "ZYADA CUSTOMERS",
    out2Sub: "Instant trust aur verified bookings",
    out3Title: "ZYADA SALES",
    out3Sub: "Automated pipeline velocity",
    out4Title: "KAM SAMAY BARBAAD",
    out4Sub: "Autonomous smooth operations",
    out5Title: "BEHTAR OPERATIONS",
    out5Sub: "Zero human lag ya lead drop",
    out6Title: "HIGHER REVENUE",
    out6Sub: "Predictable compounding scale",

    // Section 10: Contact
    sec10Tag: "[ INQUIRY CONSOLE // 10 ]",
    sec10Badge: "PROJECT DESK",
    sec10TitlePart1: "DEKHTE HAIN KYA",
    sec10TitlePart2: "aapke business ko rok raha hai.",
    sec10Sub: "Humein apne business aur current challenges ke baare me bataiye. Hum identify karenge ki sabse badi growth opportunities kahan hain.",
    mottoP1: "Understand the problem.",
    mottoP2: "Build the solution.",
    mottoP3: "Create the growth.",
    inquiryDeskTitle: "DIRECT INQUIRY DESK",
    auditTitle: "DISCOVERY PROTOCOL",
    auditDesc: "Initial 30-Min Systems Audit",
    auditBadge: "FREE AUDIT",
    contactEmail: "saturngrowthsystems@gmail.com",
    primaryPhone: "+91 79826 68530",
    alternatePhone: "+91 87440 03727",
    whatsappLink: "https://wa.me/917982668530?text=Hi%20Saturn%20Growth%20Systems%2C%20I%20would%20like%20to%20book%20a%20systems%20audit.",
    whatsappAlternateLink: "https://wa.me/918744003727?text=Hi%20Saturn%20Growth%20Systems%2C%20I%20would%20like%20to%20book%20a%20systems%20audit.",
    lblName: "Aapka Pura Naam *",
    lblComp: "Business / Company Ka Naam *",
    lblContact: "Email ya Phone Number *",
    lblBizdesc: "Aapka Business Kya Karta Hai? *",
    lblProblem: "Aapko Kaunsi Problem Solve Karni Hai?",
    phName: "e.g. Rahul Mehta",
    phComp: "e.g. Apex Enterprises ya Shivam Coaching",
    phContact: "saturngrowthsystems@gmail.com ya +91 79826 68530",
    phBizdesc: "e.g. Private school with 800+ students, ya Multi-city real estate firm...",
    phProblem: "Bataiye kahan customers drop ho rahe hain, team ka time kahan ja raha hai, ya kya automate karna chahte hain...",
    btnSend: "Growth Consultation Book Karein →",
    formSuccessTitle: "AUDIT BRIEF DISPATCH HO GAYA",
    formSuccessMsg: "Hamare Lead Growth Architect aapki request review karke agle 2 ghante me aapse contact karenge.",

    // Footer
    footerMotto: "Understand the problem. Build the solution. Create the growth.",
    footerScale: "ENGINEERED FOR COMPOUNDING SCALE"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: content[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
